export const CAR_COLORS = [
  { name: 'Pearl White', hex: '#F5F5F0' },
  { name: 'Midnight Silver', hex: '#5E5E5E' },
  { name: 'Deep Blue', hex: '#0A2A5E' },
  { name: 'Solid Black', hex: '#0B0B0C' },
  { name: 'Red Multi-Coat', hex: '#C8102E' },
  { name: 'Stealth Grey', hex: '#6E6E6E' },
];

export const CARS = [
  {
    slug: 'cybertruck',
    name: 'Cybertruck',
    model: 'Cybertruck',
    year: 2020,
    price: 79990,
    priceLabel: '$79,990.00',
    image: '/assets/cars/cybertruck.jpg',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: 'Featured',
    tagline: 'The toughest truck, built for the future.',
    description: 'The Tesla Cybertruck is an all-electric, armored utility vehicle with a nearly impenetrable exoskeleton, ultra-hard 30X cold-rolled stainless steel, and shatter-resistant Armor Glass. It delivers sports-car performance with the utility of a pickup.',
    specs: [
      { label: 'Battery', value: '123 kWh' },
      { label: 'Drive', value: 'All-Wheel Drive' },
      { label: 'Seating', value: '5 adults' },
      { label: 'Wheels', value: '20" Cyber wheels' },
      { label: 'Towing', value: '11,000 lbs' },
      { label: 'Cargo', value: '100 cu ft' },
    ],
  },
  {
    slug: 'model-s',
    name: 'Model S',
    model: 'Model S',
    year: 2022,
    price: 74990,
    priceLabel: '$74,990.00',
    image: '/assets/cars/model-s.jpg',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: 'Featured',
    tagline: 'The world’s highest-performance sedan.',
    description: 'Tesla Model S is a premium all-electric sedan that set the standard for electric performance, with a minimalist interior, a 17-inch cinematic touchscreen, and industry-leading range.',
    specs: [
      { label: 'Battery', value: '100 kWh' },
      { label: 'Drive', value: 'All-Wheel Drive' },
      { label: 'Seating', value: '5 adults' },
      { label: 'Wheels', value: '19" Tempest' },
      { label: 'Cargo', value: '28 cu ft' },
      { label: 'Display', value: '17" touchscreen' },
    ],
  },
  {
    slug: 'model-y',
    name: 'Model Y',
    model: 'Model Y',
    year: 2024,
    price: 42000,
    priceLabel: '$42,000.00',
    image: '/assets/cars/model-y.jpg',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: '',
    tagline: 'The most versatile electric crossover.',
    description: 'Tesla Model Y is a spacious all-electric crossover with versatile cargo space, an expansive glass roof, and seating for up to seven. It is engineered for safety and efficiency.',
    specs: [
      { label: 'Battery', value: '75 kWh' },
      { label: 'Drive', value: 'All-Wheel Drive' },
      { label: 'Seating', value: '5–7 adults' },
      { label: 'Wheels', value: '19" Gemini' },
      { label: 'Cargo', value: '76 cu ft' },
      { label: 'Glass roof', value: 'Tinted' },
    ],
  },
  {
    slug: 'model-x',
    name: 'Model X',
    model: 'Model X',
    year: 2021,
    price: 36000,
    priceLabel: '$36,000.00',
    image: '/assets/cars/model-x.jpg',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: '',
    tagline: 'The highest-rated SUV for safety and space.',
    description: 'Tesla Model X is a luxury all-electric SUV with iconic Falcon Wing doors, seating for up to seven, and the largest windshield in production, all wrapped in a clean, minimalist cabin.',
    specs: [
      { label: 'Battery', value: '100 kWh' },
      { label: 'Drive', value: 'All-Wheel Drive' },
      { label: 'Seating', value: '5–7 adults' },
      { label: 'Wheels', value: '20" Cyberstream' },
      { label: 'Doors', value: 'Falcon Wing' },
      { label: 'Cargo', value: '88 cu ft' },
    ],
  },
  {
    slug: 'model-3',
    name: 'Model 3 Long Range',
    model: 'Model 3',
    year: 2024,
    price: 47240,
    priceLabel: '$47,240.00',
    image: '/assets/cars/model-3.jpg',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: '',
    tagline: 'The best-selling electric sedan.',
    description: 'Tesla Model 3 Long Range is the accessible all-electric sedan that redefined the segment, with a sleek minimalist interior, long range, and fast acceleration.',
    specs: [
      { label: 'Battery', value: '75 kWh' },
      { label: 'Drive', value: 'All-Wheel Drive' },
      { label: 'Seating', value: '5 adults' },
      { label: 'Wheels', value: '18" Aero' },
      { label: 'Cargo', value: '23 cu ft' },
      { label: 'Display', value: '15" touchscreen' },
    ],
  },
  {
    slug: 'model-x-plaid',
    name: 'Model X Plaid',
    model: 'Model X',
    year: 2024,
    price: 94990,
    priceLabel: '$94,990.00',
    image: '/assets/cars/model-x-plaid.jpg',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: 'Featured',
    tagline: 'The quickest SUV ever built.',
    description: 'Tesla Model X Plaid pairs the space and signature Falcon Wing doors of Model X with tri-motor, 1,020-horsepower performance — accelerating 0–60 mph in just 2.5 seconds.',
    specs: [
      { label: 'Battery', value: '100 kWh' },
      { label: 'Drive', value: 'Tri-Motor AWD' },
      { label: 'Seating', value: '6 adults' },
      { label: 'Wheels', value: '22" Turbine' },
      { label: 'Power', value: '1,020 hp' },
      { label: '0–60 mph', value: '2.5s' },
    ],
  },
];

export function findCar(slug) {
  return CARS.find((c) => c.slug === slug) || CARS[0];
}
