export const CAR_COLORS = [
  { name: 'Pearl White', hex: '#F5F5F0' },
  { name: 'Midnight Silver', hex: '#5E5E5E' },
  { name: 'Deep Blue', hex: '#0A2A5E' },
  { name: 'Solid Black', hex: '#0B0B0C' },
  { name: 'Red Multi-Coat', hex: '#C8102E' },
  { name: 'Stealth Grey', hex: '#6E6E6E' },
];

export const CARS = [
  {
    slug: 'cybertruck',
    name: 'Cybertruck',
    model: 'Cybertruck',
    year: 2020,
    price: 79990,
    priceLabel: '$79,990.00',
    image: '/assets/inventory/cybertruck.webp',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: 'Featured',
    tagline: 'The toughest truck, built for the future.',
    description: 'The Tesla Cybertruck is an all-electric, armored utility vehicle with a nearly impenetrable exoskeleton, ultra-hard 30X cold-rolled stainless steel, and shatter-resistant Armor Glass. It delivers sports-car performance with the utility of a pickup.',
    specs: [
      { label: 'Battery', value: '123 kWh' },
      { label: 'Drive', value: 'All-Wheel Drive' },
      { label: 'Seating', value: '5 adults' },
      { label: 'Wheels', value: '20" Cyber wheels' },
      { label: 'Towing', value: '11,000 lbs' },
      { label: 'Cargo', value: '100 cu ft' },
    ],
  },
  {
    slug: 'model-s',
    name: 'Model S',
    model: 'Model S',
    year: 2022,
    price: 74990,
    priceLabel: '$74,990.00',
    image: '/assets/cars/model-s.jpg',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: 'Featured',
    tagline: 'The world’s highest-performance sedan.',
    description: 'Tesla Model S is a premium all-electric sedan that set the standard for electric performance, with a minimalist interior, a 17-inch cinematic touchscreen, and industry-leading range.',
    specs: [
      { label: 'Battery', value: '100 kWh' },
      { label: 'Drive', value: 'All-Wheel Drive' },
      { label: 'Seating', value: '5 adults' },
      { label: 'Wheels', value: '19" Tempest' },
      { label: 'Cargo', value: '28 cu ft' },
      { label: 'Display', value: '17" touchscreen' },
    ],
  },
  {
    slug: 'model-y',
    name: 'Model Y',
    model: 'Model Y',
    year: 2024,
    price: 42000,
    priceLabel: '$42,000.00',
    image: '/assets/inventory/model-y.avif',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: '',
    tagline: 'The most versatile electric crossover.',
    description: 'Tesla Model Y is a spacious all-electric crossover with versatile cargo space, an expansive glass roof, and seating for up to seven. It is engineered for safety and efficiency.',
    specs: [
      { label: 'Battery', value: '75 kWh' },
      { label: 'Drive', value: 'All-Wheel Drive' },
      { label: 'Seating', value: '5–7 adults' },
      { label: 'Wheels', value: '19" Gemini' },
      { label: 'Cargo', value: '76 cu ft' },
      { label: 'Glass roof', value: 'Tinted' },
    ],
  },
  {
    slug: 'model-x',
    name: 'Model X',
    model: 'Model X',
    year: 2021,
    price: 36000,
    priceLabel: '$36,000.00',
    image: '/assets/cars/model-x.jpg',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: '',
    tagline: 'The highest-rated SUV for safety and space.',
    description: 'Tesla Model X is a luxury all-electric SUV with iconic Falcon Wing doors, seating for up to seven, and the largest windshield in production, all wrapped in a clean, minimalist cabin.',
    specs: [
      { label: 'Battery', value: '100 kWh' },
      { label: 'Drive', value: 'All-Wheel Drive' },
      { label: 'Seating', value: '5–7 adults' },
      { label: 'Wheels', value: '20" Cyberstream' },
      { label: 'Doors', value: 'Falcon Wing' },
      { label: 'Cargo', value: '88 cu ft' },
    ],
  },
  {
    slug: 'model-3',
    name: 'Model 3 Long Range',
    model: 'Model 3',
    year: 2024,
    price: 47240,
    priceLabel: '$47,240.00',
    image: '/assets/inventory/model-3.avif',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: '',
    tagline: 'The best-selling electric sedan.',
    description: 'Tesla Model 3 Long Range is the accessible all-electric sedan that redefined the segment, with a sleek minimalist interior, long range, and fast acceleration.',
    specs: [
      { label: 'Battery', value: '75 kWh' },
      { label: 'Drive', value: 'All-Wheel Drive' },
      { label: 'Seating', value: '5 adults' },
      { label: 'Wheels', value: '18" Aero' },
      { label: 'Cargo', value: '23 cu ft' },
      { label: 'Display', value: '15" touchscreen' },
    ],
  },
  {
    slug: 'model-x-plaid',
    name: 'Model X Plaid',
    model: 'Model X',
    year: 2024,
    price: 94990,
    priceLabel: '$94,990.00',
    image: '/assets/cars/model-x-plaid.jpg',
    range: '410mi',
    accel: '3.1s',
    topSpeed: '130mph',
    badge: 'Featured',
    tagline: 'The quickest SUV ever built.',
    description: 'Tesla Model X Plaid pairs the space and signature Falcon Wing doors of Model X with tri-motor, 1,020-horsepower performance — accelerating 0–60 mph in just 2.5 seconds.',
    specs: [
      { label: 'Battery', value: '100 kWh' },
      { label: 'Drive', value: 'Tri-Motor AWD' },
      { label: 'Seating', value: '6 adults' },
      { label: 'Wheels', value: '22" Turbine' },
      { label: 'Power', value: '1,020 hp' },
      { label: '0–60 mph', value: '2.5s' },
    ],
  },
  {
    slug: 'powerwall-3',
    category: 'Battery',
    name: 'Powerwall 3',
    model: 'Powerwall',
    year: 2025,
    price: 9300,
    priceLabel: '$9,300.00',
    image: '/assets/energy/powerwall.jpg',
    badge: 'New',
    stats: [
      { label: 'Capacity', value: '13.5 kWh' },
      { label: 'Power', value: '11.5 kW' },
      { label: 'Warranty', value: '10 yrs' },
    ],
    tagline: 'Whole-home backup with integrated solar inverter.',
    description: 'Powerwall 3 is a fully integrated home battery that stores solar energy for use at night and keeps your home powered through outages. Its built-in solar inverter simplifies installation, and the Tesla app lets you monitor and control your energy in real time.',
    specs: [
      { label: 'Energy Capacity', value: '13.5 kWh' },
      { label: 'Continuous Power', value: '11.5 kW' },
      { label: 'Solar Inverter', value: 'Integrated, 6 MPPTs' },
      { label: 'Scalability', value: 'Up to 4 units' },
      { label: 'Installation', value: 'Wall or floor, indoor/outdoor' },
      { label: 'Warranty', value: '10 years' },
    ],
  },
  {
    slug: 'solar-panels',
    category: 'Solar',
    name: 'Solar Panels 8.2 kW',
    model: 'Solar Panels',
    year: 2025,
    price: 18500,
    priceLabel: '$18,500.00',
    image: '/assets/inventory/solar-panels.webp',
    stats: [
      { label: 'System Size', value: '8.2 kW' },
      { label: 'Yearly Output', value: '11,000 kWh' },
      { label: 'Warranty', value: '25 yrs' },
    ],
    tagline: 'Low-profile panels that cut your energy bill.',
    description: 'Tesla Solar Panels convert sunlight into clean electricity for your home or business. The low-profile, all-black design integrates cleanly with your roof or carport, and pairs with Powerwall to store excess energy for use any time.',
    specs: [
      { label: 'System Size', value: '8.2 kW' },
      { label: 'Panels', value: '20 × 410 W' },
      { label: 'Est. Yearly Output', value: '11,000 kWh' },
      { label: 'Mounting', value: 'Roof or carport canopy' },
      { label: 'Monitoring', value: 'Tesla app' },
      { label: 'Warranty', value: '25 years' },
    ],
  },
  {
    slug: 'solar-roof',
    category: 'Solar',
    name: 'Solar Roof',
    model: 'Solar Roof',
    year: 2025,
    price: 64000,
    priceLabel: '$64,000.00',
    image: '/assets/energy/solar-roof.jpg',
    badge: 'Featured',
    stats: [
      { label: 'System Size', value: '10 kW' },
      { label: 'Wind Rating', value: '166 mph' },
      { label: 'Warranty', value: '25 yrs' },
    ],
    tagline: 'A roof that powers your home.',
    description: 'Solar Roof replaces your existing roof with durable glass solar tiles that are nearly indistinguishable from conventional roofing. It generates clean energy while protecting your home, and works seamlessly with Powerwall for backup power.',
    specs: [
      { label: 'System Size', value: '10 kW' },
      { label: 'Tile Material', value: 'Tempered glass' },
      { label: 'Wind Rating', value: 'Class F (166 mph)' },
      { label: 'Hail Rating', value: 'Class 3' },
      { label: 'Fire Rating', value: 'Class A' },
      { label: 'Warranty', value: '25 years' },
    ],
  },
  {
    slug: 'wall-connector',
    category: 'Charging',
    name: 'Wall Connector',
    model: 'Wall Connector',
    year: 2025,
    price: 475,
    priceLabel: '$475.00',
    image: '/assets/energy/wall-connector.jpg',
    stats: [
      { label: 'Range / Hour', value: '44 mi' },
      { label: 'Power', value: '11.5 kW' },
      { label: 'Cable', value: '24 ft' },
    ],
    tagline: 'The fastest way to charge at home.',
    description: 'The Wall Connector is the most convenient charging solution for houses, apartments and workplaces. It adds up to 44 miles of range per hour, supports power sharing across multiple units, and connects to Wi-Fi for over-the-air updates.',
    specs: [
      { label: 'Max Power', value: '11.5 kW (48 A)' },
      { label: 'Charge Speed', value: 'Up to 44 mi/hr' },
      { label: 'Cable Length', value: '24 ft' },
      { label: 'Connector', value: 'NACS' },
      { label: 'Rating', value: 'Indoor / outdoor' },
      { label: 'Warranty', value: '4 years' },
    ],
  },
  {
    slug: 'supercharger-v4',
    category: 'Charging',
    name: 'Supercharger V4 Station',
    model: 'Supercharger',
    year: 2025,
    price: 185000,
    priceLabel: '$185,000.00',
    image: '/assets/energy/supercharger.jpg',
    badge: 'Business',
    stats: [
      { label: 'Peak Power', value: '250 kW' },
      { label: 'Stalls', value: '4' },
      { label: 'Uptime', value: '99.9%' },
    ],
    tagline: 'High-power charging for your business.',
    description: 'Bring Supercharging to your property with a four-stall V4 station. Longer cables reach any EV, the built-in payment terminal accepts cards, and Tesla handles installation, monitoring and maintenance so your site stays online.',
    specs: [
      { label: 'Stalls', value: '4 V4 posts' },
      { label: 'Peak Power', value: '250 kW per stall' },
      { label: 'Compatibility', value: 'NACS & CCS' },
      { label: 'Payments', value: 'Integrated card reader' },
      { label: 'Monitoring', value: '24/7 remote' },
      { label: 'Service', value: 'Included' },
    ],
  },
];

export const CATEGORIES = ['Vehicles', 'Solar', 'Battery', 'Charging'];

export function categoryOf(item) {
  return item.category || 'Vehicles';
}

// Three headline figures shown on cards and the detail page.
export function headlineStats(item) {
  return item.stats || [
    { label: 'Range', value: item.range },
    { label: '0-60 mph', value: item.accel },
    { label: 'Top Speed', value: item.topSpeed },
  ];
}

export function findCar(slug) {
  return CARS.find((c) => c.slug === slug) || CARS[0];
}
